name: Deploy Cyberprism Web app

on:
  push:
    branches:
      - feature/mvp-web

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      run: echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key && chmod 600 private_key

    - name: Connect to EC2
      run: ssh -o StrictHostKeyChecking=no -i private_key ubuntu@54.216.70.166 'cd /var/www/cyberprism-web'

    - name: Pull latest code
      run: ssh -o StrictHostKeyChecking=no -i private_key ubuntu@54.216.70.166 'cd /var/www/cyberprism-web && sudo git pull'

    - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18.18.2
          
    - name: Install dependencies
      run: ssh -o StrictHostKeyChecking=no -i private_key ubuntu@54.216.70.166 'cd /var/www/cyberprism-web && sudo npm install'

    - name: Build the app
      run: ssh -o StrictHostKeyChecking=no -i private_key ubuntu@54.216.70.166 'cd /var/www/cyberprism-web && sudo npm run build'

    - name: Restart app with PM2
      run: ssh -o StrictHostKeyChecking=no -i private_key ubuntu@54.216.70.166 'pm2 restart your-app'